WITH CRITICA AS (
	SELECT	/*+ Materialize */	
			DISTINCT CM_ORDECRIT.ORCRSESU AS NIS,
			99 AS CD_EMPRESA
	FROM CHILQUIN.CM_ORDECRIT
	JOIN CHILQUIN.SERVSUSC ON SERVSUSC.SESUNUSE = CM_ORDECRIT.ORCRSESU
	JOIN CHILQUIN.PERICOSE ON PERICOSE.PECSCONS = CM_ORDECRIT.ORCRPECO
	JOIN CHILQUIN.PERIFACT ON PERIFACT.PEFACODI=PERICOSE.PECSCONS
	JOIN CHILQUIN.OR_ORDER_ACTIVITY ON OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID = CM_ORDECRIT.ORCRACTI
	JOIN CHILQUIN.OR_ORDER ON OR_ORDER.ORDER_ID = OR_ORDER_ACTIVITY.ORDER_ID	
	WHERE  PERICOSE.PECSPROC='S'
	AND PERIFACT.PEFAACTU<>'-'
	AND SERVSUSC.SESUPLFA  IN (57,59,60,62,64,65,76,78,127,129,130,131,132,133,134)
	AND OR_ORDER.ORDER_STATUS_ID < 8
		
)
,CONSUMOS AS (
	SELECT      /*+ Materialize */	
				CD_EMPRESA,
				--ID,
	            NIS,
	            CONTRATO,
	            --PERIODO_CONSUMO,
	            --PERIODO_FACTURACION,
	            --MES,
	            --ANIO,
	            --MEDIDOR,
	            SUM(CONSUMO) AS CONSUMO,
	            TIPO_CONSUMO,
	            CICLO,
	            ROW_NUMBER() OVER (PARTITION BY NIS, TIPO_CONSUMO ORDER BY ANIO DESC,MES DESC) AS RANK
	FROM (
		SELECT      X.CD_EMPRESA,
					CONSSESU.COSSSESU ||'-' || ELMESESU.EMSSELME AS ID,
					CONSSESU.COSSSESU AS NIS,
					SERVSUSC.SESUSUSC AS CONTRATO,
					CONSSESU.COSSPECS AS PERIODO_CONSUMO,                            
					CONSSESU.COSSPEFA AS PERIODO_FACTURACION,           
					CONSSESU.COSSTCON AS TIPO_CONSUMO,
					SERVSUSC.SESUCICL AS CICLO,
					PF.PEFAMES AS MES,
					PF.PEFAANO AS ANIO,
					ELMESESU.EMSSCOEM AS MEDIDOR,
					ROUND(CONSSESU.COSSCOCA, 0) AS CONSUMO,
					ROW_NUMBER() OVER (PARTITION BY CONSSESU.COSSSESU, CONSSESU.COSSPECS, CONSSESU.COSSTCON ORDER BY CONSSESU.COSSFERE DESC) AS rnk1,
					ROW_NUMBER() OVER (PARTITION BY CONSSESU.COSSSESU ORDER BY CONSSESU.COSSPECS DESC,CONSSESU.COSSFERE DESC) AS rnk2
		FROM CHILQUIN.CONSSESU
		JOIN (
			SELECT *
			FROM(
				SELECT	PERIFACT.PEFACODI,
						PERIFACT.PEFAANO,
						PERIFACT.PEFAMES,
						PERIFACT.PEFACICL AS CICLO,
						PERIFACT.PEFAFIMO,
						PERIFACT.PEFAFIMO AS FC_ANT,
						PERIFACT.PEFAANO * 100 + PERIFACT.PEFAMES AS PERIODO,
						PEFAACTU,
						RANK() OVER(PARTITION BY PERIFACT.PEFACICL ORDER BY PERIFACT.PEFAANO * 100 + PERIFACT.PEFAMES DESC) RNK
						--RANK() OVER(PARTITION BY PERIFACT.PEFACICL ORDER BY PERIFACT.PEFAANO * 100 + PERIFACT.PEFAMES ASC) RNK
				FROM 	CHILQUIN.PERIFACT                                                                      
				WHERE	PERIFACT.PEFACICL BETWEEN 1 AND 20
				AND	PERIFACT.PEFAACTU IN ('-', 'S')
			) WHERE RNK IN (1,2,3,4,5,6) -- Meses	      
		) PF ON PF.PEFACODI = COSSPECS     
		JOIN CHILQUIN.MECACONS ON CONSSESU.COSSMECC = MECACONS.MECCCODI
		JOIN CHILQUIN.ELMESESU ON CONSSESU.COSSELME = ELMESESU.EMSSELME AND CONSSESU.COSSSESU = ELMESESU.EMSSSESU 
		JOIN CHILQUIN.SERVSUSC  ON CONSSESU.COSSSESU = SERVSUSC.SESUNUSE 
		JOIN CRITICA X ON SERVSUSC.SESUNUSE =  X.NIS AND X.CD_EMPRESA = 99
		WHERE       CONSSESU.COSSMECC NOT IN (2,4,19) 
		--AND CONSSESU.COSSSESU = 1022077
				
	) 
	WHERE RNK1 = 1
	GROUP BY 	CD_EMPRESA,
				ID,
	            NIS,
	            CONTRATO,
	            MES,
	            ANIO,
	            MEDIDOR,
	            TIPO_CONSUMO,
	            CICLO
	--ORDER BY NIS, ANIO ASC, MES ASC            
)

, Consumo6MPvt AS (
    SELECT *
      FROM CONSUMOS 
      pivot (
            sum(CONSUMO)
            FOR RANK IN (1  AS "CONS_MES_ACTUAL",
                          2  AS "CONS_MES_ANTERIOR",
                          3  AS "CONS_MES_3",
                          4  AS "CONS_MES_4",
                          5  AS "CONS_MES_5",
                          6  AS "CONS_MES_6")
            )
)


,PREVIA AS (
	SELECT 	A. NIS,
			A.TIPO_CONSUMO,
			A.CICLO,
			A.CONS_MES_ACTUAL,
			A.CONS_MES_ANTERIOR,
			A.CONS_MES_3,
			A.CONS_MES_4,
			A.CONS_MES_5,
			A.CONS_MES_6,			
			--ROUND( GREATEST( ABS(COALESCE( (A.CONS_MES_ACTUAL - A.CONS_MES_ANTERIOR) / NULLIF(A.CONS_MES_ANTERIOR, 0) , 0)), ABS(COALESCE( (A.CONS_MES_ANTERIOR - A.CONS_MES_ACTUAL) / NULLIF(A.CONS_MES_ACTUAL, 0) , 0)) ), 2) AS QUIEBRE
			ROUND(COALESCE( (A.CONS_MES_ACTUAL - A.CONS_MES_ANTERIOR) / NULLIF(A.CONS_MES_ANTERIOR, 0) , 0),  2) AS QUIEBRE
	FROM Consumo6MPvt A
	--JOIN consumos b ON a.NIS = b.NIS AND A.TIPO_CONSUMO = B.TIPO_CONSUMO AND b.RANK = 1
	--WHERE a.RANK = 2
	)
	
	
,Inspecciones AS (
    SELECT oa.PRODUCT_ID,
           o.CAUSAL_ID,
           gc.DESCRIPTION ULTIMA_CAUSAL,
           o.EXECUTION_FINAL_DATE FECHA_INSPECCION,
           o.ORDER_ID,
           ROW_NUMBER() OVER (PARTITION BY oa.PRODUCT_ID ORDER BY o.LEGALIZATION_DATE DESC ) ORORD
      FROM PREVIA
      JOIN CHILQUIN.OR_EXTERN_SYSTEMS_ID oa ON oa.PRODUCT_ID = PREVIA.NIS
      --FROM 
      JOIN CHILQUIN.OR_ORDER o ON oa.ORDER_ID = o.ORDER_ID        
      JOIN CHILQUIN.GE_CAUSAL gc ON gc.CAUSAL_ID = o.CAUSAL_ID 
      JOIN CHILQUIN.OR_OPERATING_UNIT u ON u.OPERATING_UNIT_ID = o.OPERATING_UNIT_ID
      --JOIN PREVIA ON oa.PRODUCT_ID = PREVIA.NIS
     WHERE o.TASK_TYPE_ID IN (10235, 10245, 10260)
       AND o.ORDER_STATUS_ID = 8
       AND (o.CAUSAL_ID IN (8168,8169,8170,8171,8172,8173,8235,8268,8269)
        OR (o.CAUSAL_ID = 8177 AND u.NAME LIKE 'MA_%'))  
       --AND oa.PRODUCT_ID IN (:PRODUCTOS)
)
, Efectivas AS (
    SELECT * 
      FROM Inspecciones i       
     WHERE i.ORORD = 1
)

	
,INSPEC_REGISTRADA AS (
    SELECT oa.PRODUCT_ID,
           --o.CAUSAL_ID,
           --gc.DESCRIPTION ULTIMA_CAUSAL,
           o.CREATED_DATE AS FECHA_CREACION,
           o.ORDER_STATUS_ID AS ESTADO_REGISTRADA,
           o.ORDER_ID AS ORDEN_REGIS,
           ROW_NUMBER() OVER (PARTITION BY oa.PRODUCT_ID ORDER BY o.CREATED_DATE DESC ) ORORD
      FROM PREVIA
      JOIN CHILQUIN.OR_EXTERN_SYSTEMS_ID oa ON oa.PRODUCT_ID = PREVIA.NIS
      --FROM 
      JOIN CHILQUIN.OR_ORDER o ON oa.ORDER_ID = o.ORDER_ID        
      --JOIN CHILQUIN.GE_CAUSAL gc ON gc.CAUSAL_ID = o.CAUSAL_ID 
      --JOIN CHILQUIN.OR_OPERATING_UNIT u ON u.OPERATING_UNIT_ID = o.OPERATING_UNIT_ID
      --JOIN PREVIA ON oa.PRODUCT_ID = PREVIA.NIS
     WHERE o.TASK_TYPE_ID IN (10235, 10245, 10260)
       AND o.ORDER_STATUS_ID IN (0,5)
       --AND (o.CAUSAL_ID IN (8168,8169,8170,8171,8172,8173,8235,8268,8269)
        --OR (o.CAUSAL_ID = 8177 AND u.NAME LIKE 'MA_%'))  
       --AND oa.PRODUCT_ID IN (:PRODUCTOS)
)


, ULT_REGIS AS (
    SELECT * 
      FROM INSPEC_REGISTRADA i       
     WHERE i.ORORD = 1
)	
	

, FINAL AS (
	SELECT PREVIA.*,
		   Efectivas.CAUSAL_ID,
		   Efectivas.ULTIMA_CAUSAL,
		   Efectivas.FECHA_INSPECCION,
		   Efectivas.ORDER_ID,
		   ULT_REGIS.FECHA_CREACION,
		   ULT_REGIS.ESTADO_REGISTRADA,
		   ULT_REGIS.ORDEN_REGIS,
	       pl.DESCRIPTION TARIFA,
           ca.CATEDESC CATEGORIA,
           sc.SUCADESC SUBCATEGORIA

   
	FROM PREVIA
	LEFT
	JOIN CHILQUIN.PR_PRODUCT pr         ON PREVIA.NIS = pr.PRODUCT_ID
	LEFT
	JOIN CHILQUIN.CC_COMMERCIAL_PLAN pl ON pl.COMMERCIAL_PLAN_ID = pr.COMMERCIAL_PLAN_ID 
	LEFT
    JOIN CHILQUIN.CATEGORI ca ON ca.CATECODI = pr.CATEGORY_ID
    LEFT
    JOIN CHILQUIN.SUBCATEG sc ON sc.SUCACODI = pr.SUBCATEGORY_ID AND sc.SUCACATE = pr.CATEGORY_ID
    LEFT
    JOIN EFECTIVAS ON EFECTIVAS.PRODUCT_ID = PREVIA.NIS
    LEFT
    JOIN ULT_REGIS ON ULT_REGIS.PRODUCT_ID = PREVIA.NIS



)


SELECT * FROM FINAL